FROM hashicorp/terraform:0.12.29 as terraform
FROM golang:1.14.6-buster as go

RUN go get -u github.com/dmitry-at-hyla/liche

FROM alpine:3.7

ENV AWSCLI_VERSION 1.18.4

RUN apk add --update \
  git make bash \
  && apk --purge -v del py-pip \
  && rm -rf /var/cache/apk/* \
  && rm -rf $HOME/.cache

COPY --from=terraform /bin/terraform /usr/bin

ENV GO_BIN /go/bin
ENV PATH "$GO_BIN:$PATH"

COPY --from=go /go/bin $GO_BIN

ENV BIN_3SCALE /opt/3scale/bin
ENV PATH "$BIN_3SCALE:$PATH"

ADD bin/ $BIN_3SCALE
RUN chmod -R 0755 $BIN_3SCALE
